// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ElExampleColumns holds the columns for the "el_example" table.
	ElExampleColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 64},
		{Name: "summary", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "create_time", Type: field.TypeTime, Nullable: true},
		{Name: "update_time", Type: field.TypeTime, Nullable: true},
	}
	// ElExampleTable holds the schema information for the "el_example" table.
	ElExampleTable = &schema.Table{
		Name:       "el_example",
		Columns:    ElExampleColumns,
		PrimaryKey: []*schema.Column{ElExampleColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ElExampleTable,
	}
)

func init() {
	ElExampleTable.Annotation = &entsql.Annotation{
		Table: "el_example",
	}
}
